// components/home/HomeHero/index.tsx
import React from "react";
import Image from "next/image";
import styles from "./styles.module.scss";

const HomeHero = () => {
  return (
    <section className={styles["hero"]}>
      <div className={styles["hero-container"]}>
        {/* <div className={styles["hero-description"]}>
          <h1>¿Quiénes somos?</h1>
          <h2>
            Somos una organización independiente de estudiantes y graduades, que
            tenemos como fin promover el pensamiento crítico y la psicología
            científica, formarnos entre los integrantes en temas afines y
            reclamar por una formación actualizada, plural y científica.
          </h2>
        </div> */}
        <div className={styles["hero-image"]}>
          <Image
            src="/images/hero.svg"
            width="500"
            height="500"
            alt="MEPC cover"
          />
        </div>
      </div>
    </section>
  );
};

export default HomeHero;

// components/HomeHero.vue
<template>
  <section id="hero">
    <div class="container-hero">
      <div class="hero-description">
        <h1>¿Quiénes somos?</h1>
        <h2>
          Somos una organización independiente de <br />estudiantes y graduades,
          que tenemos como<br />
          fin promover el pensamiento crítico y la<br />
          psicología científica, formarnos entre los<br />
          integrantes en temas afines y reclamar por<br />
          una formación actualizada, plural y científica.
        </h2>
      </div>
      <div class="hero-image">
        <img src="./assets/images/hero.svg" alt="Logo de portada de MEPC" />
      </div>
    </div>
  </section>
</template>
