// components/home/HomeCollaboration/index.tsx
import React from "react";
import contents from "../../../lib/content.json";
import Image from "next/image";
import styles from "./styles.module.scss";

const HomeCollaboration = () => {
  return (
    <section id={styles.collaboration}>
      <div className={styles["collaboration__title--primary"]}>
        <h1>¿Cómo colaborar?</h1>
        <hr />
      </div>
      {contents.collaboration.map((content) => (
        <div className={styles.collaboration__content} key={content.title}>
          <div className={styles.collaboration__image}>
            <Image
              width="100"
              height="100"
              src={"/images/" + content.img}
              alt={content.alt}
            />
          </div>
          <div className={styles.collaboration__text}>
            <div>
              <h2 className={styles.collaboration__title}>{content.title}</h2>
              <p
                className={styles.collaboration__description}
                dangerouslySetInnerHTML={{ __html: content.description }}
              />
            </div>
          </div>
        </div>
      ))}
    </section>
  );
};

export default HomeCollaboration;

// components/HomeCollaboration.vue
<template>
  <section id="collaboration">
    <div class="collaboration__title--primary">
      <h1>¿Cómo colaborar?</h1>
      <hr />
    </div>
    <div
      class="collaboration__content"
      v-for="content in content.collaboration"
      :key="content.title"
    >
      <div class="collaboration__image">
        <img
          :src="require('./assets/images/' + content.img)"
          :alt="content.alt"
        />
      </div>
      <div class="collaboration__text">
        <div>
          <h2 class="collaboration__title">{{ content.title }}</h2>
          <p
            class="collaboration__description"
            v-html="content.description"
          ></p>
          .
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import content from '../lib/content.json'

export default {
  data() {
    return {
      content: content,
    }
  },
}
</script>

<style lang="scss">
.collaboration__title--primary {
  @include titles;
}

.collaboration__content {
  color: $color__text;
  display: flex;
  flex-direction: row;
  justify-content: space-evenly;

  @media (max-width: $breakpoint--md) {
    flex-direction: column;
    align-items: center;
  }

  .collaboration__image {
    img {
      width: 10rem;
      max-width: 344px;
      height: auto;
      border-radius: 50%;
    }
  }

  .collaboration__text {
    flex-basis: 60%;
    color: $color__text;
    display: flex;
    text-align: left;

    @media (max-width: $breakpoint--md) {
      padding: 0 1rem 0 1rem;
      text-align: center;
    }

    .collaboration__title {
      margin: 1rem 0 1rem 0;
    }

    .collaboration__description {
      margin: 1rem 0 1rem 0;
    }
  }
}
</style>
