// components/HomeHero.vue
<template>
  <section id="hero">
    <div class="container-hero">
      <div class="hero-description">
        <h1>¿Quiénes somos?</h1>
        <h2>
          Somos una organización independiente de <br />estudiantes y graduades,
          que tenemos como<br />
          fin promover el pensamiento crítico y la<br />
          psicología científica, formarnos entre los<br />
          integrantes en temas afines y reclamar por<br />
          una formación actualizada, plural y científica.
        </h2>
      </div>
      <div class="hero-image">
        <img src="./assets/images/hero.svg" alt="Logo de portada de MEPC" />
      </div>
    </div>
  </section>
</template>

// components/HomeHero/index.tsx
import React from "react";
import Image from "next/image";

import styles from "./styles.module.scss";

const HomeHero = () => {
  return (
    <section id={styles.hero}>
      <div className={styles.hero__container}>
        <div className={styles.hero__description}>
          <h1>¿Quiénes somos?</h1>
          <h2>
            Somos una organización independiente de estudiantes y graduades, que
            tenemos como fin promover el pensamiento crítico y la psicología
            científica, formarnos entre los integrantes en temas afines y
            reclamar por una formación actualizada, plural y científica.
          </h2>
        </div>
        <div className={styles.hero__image}>
          <Image
            src="/images/hero.svg"
            width="300"
            height="300"
            alt="MEPC cover"
          />
        </div>
      </div>
    </section>
  );
};

export default HomeHero;
